# Site settings
name: Blogs
email: hhao9483@gmail.com
author: Jason Hao
url: https://github.com/jasonhhao
resume_site: https://www.linkedin.com/in/jason-hao/
github: https://github.com/jasonhhao
baseurl: ""
description: 
meta_description: 
motto: 
banner:

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: jasonhhao

# Build settings
markdown: kramdown

#baidu_analysis:

